
import { Testimonial } from "./types";

export const testimonials: Testimonial[] = [
  {
    id: 1,
    name: "Carla Mendes",
    rating: 5,
    content: "Foi incrível! Meu marido ficou emocionado com a música, as palavras descreveram perfeitamente nossa história. Ele até chorou! Valeu cada centavo e a música ficará para sempre em nossas memórias.",
    date: "12/05/2024",
    imageUrl: "https://randomuser.me/api/portraits/women/38.jpg",
    relationship: "Para o marido",
  },
  {
    id: 2,
    name: "Ricardo Alves",
    rating: 5,
    content: "Fiz uma surpresa para minha esposa em nosso aniversário de casamento. A música ficou perfeita e superou todas as minhas expectativas. Ver a expressão no rosto dela quando a música começou a tocar foi impagável.",
    date: "23/04/2024",
    imageUrl: "https://randomuser.me/api/portraits/men/45.jpg",
    relationship: "Para a esposa",
  },
  {
    id: 3,
    name: "Amanda Costa",
    rating: 4,
    content: "A composição ficou linda! Presenteei minha mãe no dia das mães e ela adorou. A música capturou perfeitamente nossa relação e as memórias que compartilhamos juntas.",
    date: "10/05/2024",
    imageUrl: "https://randomuser.me/api/portraits/women/43.jpg",
    relationship: "Para a mãe",
  },
  {
    id: 4,
    name: "Lucas Santos",
    rating: 5,
    content: "Inacreditável como transformaram minha história em uma música tão especial. Minha noiva ficou sem palavras quando ouviu. Já estamos usando a música para o nosso casamento!",
    date: "17/03/2024",
    imageUrl: "https://randomuser.me/api/portraits/men/36.jpg",
    relationship: "Para a noiva",
  },
  {
    id: 5,
    name: "Beatriz Lima",
    rating: 5,
    content: "Fiz como presente para meu filho que está morando longe. A música expressou todo o amor e saudade que sinto. Ele me ligou chorando após ouvir. Um presente que aproxima mesmo à distância.",
    date: "05/04/2024",
    imageUrl: "https://randomuser.me/api/portraits/women/41.jpg",
    relationship: "Para o filho",
  },
  {
    id: 6,
    name: "Gabriel Moreira",
    rating: 4,
    content: "Surpreendi minha namorada em nosso aniversário de namoro. Ela não esperava algo tão pessoal e único. A música conseguiu transmitir todos os sentimentos que às vezes tenho dificuldade de expressar.",
    date: "28/02/2024",
    imageUrl: "https://randomuser.me/api/portraits/men/53.jpg",
    relationship: "Para a namorada",
  },
  {
    id: 7,
    name: "Marina Soares",
    rating: 5,
    content: "Dei de presente para meu pai no aniversário dele. Ele é um homem de poucas palavras, mas percebi o quanto ficou emocionado. Ver meu pai se emocionar assim foi um momento que jamais esquecerei.",
    date: "14/04/2024",
    imageUrl: "https://randomuser.me/api/portraits/women/48.jpg",
    relationship: "Para o pai",
  },
  {
    id: 8,
    name: "Rodrigo Pereira",
    rating: 5,
    content: "Fiz uma música para comemorar 25 anos de casamento. Minha esposa não conseguiu conter as lágrimas. A qualidade da produção é impressionante, parece uma música profissional de rádio.",
    date: "03/05/2024",
    imageUrl: "https://randomuser.me/api/portraits/men/35.jpg",
    relationship: "Para a esposa",
  },
  {
    id: 9,
    name: "Fernanda Oliveira",
    rating: 5,
    content: "Encomendei uma música para minha melhor amiga que está passando por um momento difícil. Ela me disse que ouve a música todos os dias e que a ajuda a seguir em frente. O poder da música é incrível!",
    date: "19/03/2024",
    imageUrl: "https://randomuser.me/api/portraits/women/37.jpg",
    relationship: "Para uma amiga",
  }
];
