// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://afybpsjzhzhrxlhlpxyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmeWJwc2p6aHpocnhsaGxweHl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwOTI3MjEsImV4cCI6MjA1NjY2ODcyMX0.xRTolYeT2B0KZefb_pxZdREi87G7F34XdFBywkPGIGA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);